import os
import uuid
import logging
import httpx
import google.auth
from google.auth.transport.requests import Request as GoogleRequest
from contextlib import contextmanager

logger = logging.getLogger("dialogflow_client")

# ── 1. Active Test Tracker ──────────────────────────────────────────
# Used to capture tool calls made sequentially by the agent during API tests.
class TestRunTracker:
    def __init__(self):
        self.active_scenario_id = None
        self.captured_tool_calls = []

    @contextmanager
    def capture(self, scenario_id: str):
        self.active_scenario_id = scenario_id
        self.captured_tool_calls = []
        logger.info(f"Started capturing tool calls for scenario {scenario_id}")
        try:
            yield
        finally:
            logger.info(f"Stopped capturing tool calls for scenario {scenario_id}. Captured {len(self.captured_tool_calls)} calls.")
            self.active_scenario_id = None

    def log_tool_call(self, name: str, arguments: dict):
        if self.active_scenario_id:
            logger.info(f"Captured tool call: {name} with arguments: {arguments}")
            self.captured_tool_calls.append({
                "name": name,
                "arguments": arguments
            })

# Global singleton tracker instance
tracker = TestRunTracker()


# ── 2. Dialogflow CX Client Wrapper ─────────────────────────────────

def query_aid_assist(
    text: str,
    project_id: str = None,
    location: str = None,
    agent_id: str = None,
    session_id: str = None
) -> str:
    """Send a query to the live AidAssist agent via the Dialogflow CX REST API.
    
    Args:
        text: The user message to send to the agent.
        project_id: GCP project ID override.
        location: GCP location override.
        agent_id: Dialogflow CX Agent ID override.
        session_id: The session ID to maintain conversation state.
        
    Returns:
        The text response generated by the agent.
    """
    project_id = project_id or os.getenv("GOOGLE_CLOUD_PROJECT", "agent-sentinel-498916")
    location = location or os.getenv("GOOGLE_CLOUD_LOCATION", "us-central1")
    agent_id = agent_id or os.getenv("AIDASSIST_AGENT_ID", "agent_1781027265714")
    
    session_id = session_id or f"sentinel_session_{uuid.uuid4().hex[:12]}"
    
    # 1. Obtain Google Application Default Credentials (ADC)
    # This automatically picks up IAM permissions on Cloud Run or local gcloud auth
    credentials, _ = google.auth.default(
        scopes=["https://www.googleapis.com/auth/cloud-platform"]
    )
    if not credentials.valid:
        credentials.refresh(GoogleRequest())
        
    # 2. Build the regional endpoint and endpoint URL
    if location == "global":
        host = "global-dialogflow.googleapis.com"
    else:
        host = f"{location}-dialogflow.googleapis.com"
        
    url = f"https://{host}/v3/projects/{project_id}/locations/{location}/agents/{agent_id}/sessions/{session_id}:detectIntent"
    
    # 3. Build detectIntent payload
    body = {
        "queryInput": {
            "text": {
                "text": text
            },
            "languageCode": "en"
        }
    }
    
    headers = {
        "Authorization": f"Bearer {credentials.token}",
        "Content-Type": "application/json"
    }
    
    logger.info(f"Sending query to Dialogflow CX API: '{text}' [session: {session_id}]")
    
    # 4. Execute the HTTP POST request synchronously (with a 30s timeout)
    with httpx.Client(timeout=30.0) as client:
        response = client.post(url, json=body, headers=headers)
        if response.status_code != 200:
            logger.error(f"Dialogflow CX API Error {response.status_code}: {response.text}")
            response.raise_for_status()
            
        res_data = response.json()
        
    # 5. Extract text responses from responseMessages list
    response_messages = res_data.get("queryResult", {}).get("responseMessages", [])
    text_segments = []
    
    for msg in response_messages:
        text_obj = msg.get("text", {})
        if text_obj and text_obj.get("text"):
            text_segments.extend(text_obj.get("text"))
            
    agent_response = " ".join(text_segments)
    logger.info(f"Received response from Dialogflow CX: '{agent_response}'")
    return agent_response
