import os
import uuid
import logging
from contextlib import contextmanager
from google.cloud import dialogflowcx_v3

logger = logging.getLogger("dialogflow_client")

# ── 1. Active Test Tracker ──────────────────────────────────────────
# Used to capture tool calls made sequentially by the agent during API tests.
class TestRunTracker:
    def __init__(self):
        self.active_scenario_id = None
        self.captured_tool_calls = []

    @contextmanager
    def capture(self, scenario_id: str):
        self.active_scenario_id = scenario_id
        self.captured_tool_calls = []
        logger.info(f"Started capturing tool calls for scenario {scenario_id}")
        try:
            yield
        finally:
            logger.info(f"Stopped capturing tool calls for scenario {scenario_id}. Captured {len(self.captured_tool_calls)} calls.")
            self.active_scenario_id = None

    def log_tool_call(self, name: str, arguments: dict):
        if self.active_scenario_id:
            logger.info(f"Captured tool call: {name} with arguments: {arguments}")
            self.captured_tool_calls.append({
                "name": name,
                "arguments": arguments
            })

# Global singleton tracker instance
tracker = TestRunTracker()


# ── 2. Dialogflow CX Client Wrapper ────────────────
# Queries a Conversational Agent (Dialogflow CX)

def query_agent(
    text: str,
    project_id: str = None,
    location: str = None,
    agent_id: str = None,
    session_id: str = None,
) -> str:
    """Send a query to a Dialogflow CX agent.
    
    Args:
        text: The user message to send to the agent.
        project_id: GCP project ID.
        location: GCP location.
        agent_id: The Dialogflow CX Agent ID.
        session_id: A unique session ID to maintain conversation state.
        
    Returns:
        The text response generated by the agent.
    """
    project_id = project_id or os.getenv("GOOGLE_CLOUD_PROJECT", "agent-sentinel-498916")
    location = location or os.getenv("GOOGLE_CLOUD_LOCATION", "us-central1")
    agent_id = agent_id or os.getenv("AIDASSIST_AGENT_ID") or os.getenv("DIALOGFLOW_AGENT_ID", "3f4be9c4-06b8-4287-9c38-864e73681191")
    session_id = session_id or f"sentinel_test_{uuid.uuid4().hex[:12]}"

    # Define the client endpoint based on location
    client_options = None
    if location != 'global':
        api_endpoint = f"{location}-dialogflow.googleapis.com:443"
        client_options = {"api_endpoint": api_endpoint}
    
    session_client = dialogflowcx_v3.SessionsClient(client_options=client_options)
    
    # Construct the session path
    session_path = f"projects/{project_id}/locations/{location}/agents/{agent_id}/sessions/{session_id}"
    
    # Construct the request
    text_input = dialogflowcx_v3.TextInput(text=text)
    query_input = dialogflowcx_v3.QueryInput(text=text_input, language_code="en")
    request = dialogflowcx_v3.DetectIntentRequest(
        session=session_path,
        query_input=query_input
    )
    logger.info(f"Sending query to Dialogflow. Path: {session_path}, options: {client_options}")
    logger.info(f"Sending query to Dialogflow Agent {agent_id}: '{text}' [session: {session_id}]")
    
    response = session_client.detect_intent(request=request)
    
    # Extract the response text
    response_messages = response.query_result.response_messages
    text_segments = []
    
    for message in response_messages:
        if message.text:
            text_segments.append(message.text.text[0])
            
        # We can also capture tools/playbook invocations if they are exposed in the CX response,
        # but for now we focus on the text output.
            
    agent_response = " ".join(text_segments).strip()
    logger.info(f"Received response from Dialogflow Agent: '{agent_response}'")
    return agent_response


def query_target_agent(
    text: str,
    project_id: str = None,
    location: str = None,
    agent_id: str = None,
    session_id: str = None,
) -> str:
    """Send an attack message to the target agent (e.g., AidAssist).
    Uses a unique session_id per test scenario for isolation."""
    # Resolve logical agent keys to real UUIDs from environment
    if agent_id == "aidassist":
        agent_id = os.getenv("AIDASSIST_AGENT_ID")
    elif agent_id == "hr_assistant":
        agent_id = os.getenv("HR_AGENT_ID") or os.getenv("AIDASSIST_AGENT_ID")
    elif agent_id == "it_helpdesk":
        agent_id = os.getenv("IT_AGENT_ID") or os.getenv("AIDASSIST_AGENT_ID")
    elif agent_id == "finance_advisor":
        agent_id = os.getenv("FINANCE_AGENT_ID") or os.getenv("AIDASSIST_AGENT_ID")
        
    agent_id = agent_id or os.getenv("AIDASSIST_AGENT_ID")
    session_id = session_id or f"target_{uuid.uuid4().hex[:12]}"
    return query_agent(
        text=text,
        project_id=project_id,
        location=location,
        agent_id=agent_id,
        session_id=session_id,
    )


def query_qacommander(
    text: str,
    project_id: str = None,
    location: str = None,
    session_id: str = None,
) -> str:
    """Send a message to QACommander to generate dynamic attack scenarios.
    Returns the raw JSON response from QACommander."""
    agent_id = os.getenv("QACOMMANDER_AGENT_ID")
    if not agent_id:
        raise ValueError("QACOMMANDER_AGENT_ID env var not set")
    session_id = session_id or f"commander_{uuid.uuid4().hex[:12]}"
    return query_agent(
        text=text,
        project_id=project_id,
        location=location,
        agent_id=agent_id,
        session_id=session_id,
    )

